# Generated by Django 5.0.6 on 2024-06-24 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='location',
            field=models.URLField(blank=True, null=True),
        ),
    ]
