# Generated by Django 5.0.6 on 2024-06-24 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_postmodel_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='location_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='location',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
