# Generated by Django 5.0.6 on 2024-06-29 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_postmodel_location_url_alter_postmodel_location'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommentModel',
            new_name='CommentUserPostRelation',
        ),
        migrations.RenameModel(
            old_name='FollowRelation',
            new_name='FollowUserRelation',
        ),
    ]
