# Generated by Django 5.0.6 on 2024-07-11 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_commentmodel_commentuserpostrelation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentuserpostrelation',
            name='to_user',
        ),
    ]
