# Generated by Django 5.0.6 on 2024-07-15 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_commentuserpostrelation_to_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='followuserrelation',
            options={'verbose_name': 'Follow', 'verbose_name_plural': 'Follows'},
        ),
    ]
