# Generated by Django 5.0.6 on 2024-07-23 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_followuserrelation_creation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='profile_image',
            field=models.ImageField(blank=True, default='web/static/img/default-profile.png', null=True, upload_to='pp/'),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='post',
            field=models.ImageField(upload_to='posts/'),
        ),
    ]
