# Generated by Django 5.0.6 on 2024-07-23 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_customusermodel_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='profile_image',
            field=models.ImageField(blank=True, default='/web/static/img/default-profile.png', null=True, upload_to='pp/'),
        ),
    ]
