# Generated by Django 5.0.6 on 2024-07-25 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_customusermodel_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='profile_image',
            field=models.ImageField(blank=True, default='/web/static/img/default-profile.png', null=True, upload_to='instakilogram/uploads/pp/'),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='post',
            field=models.ImageField(upload_to='instakilogram/uploads/posts/'),
        ),
    ]
