# Generated by Django 5.0.6 on 2024-07-29 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_notificationmodel_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationmodel',
            name='key',
            field=models.CharField(choices=[('follow', 'Follow'), ('like', 'Like'), ('comment', 'Comment'), ('save', 'Save'), ('tag', 'Tag')], max_length=128),
        ),
    ]
