# Generated by Django 5.0.6 on 2024-07-29 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_notificationmodel_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificationmodel',
            old_name='sender',
            new_name='committer',
        ),
        migrations.RenameField(
            model_name='notificationmodel',
            old_name='user',
            new_name='recipient',
        ),
    ]
