# Generated by Django 5.0.6 on 2024-07-29 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_commentnotification_follownotificationmodel_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommentNotification',
            new_name='CommentNotificationModel',
        ),
        migrations.RenameModel(
            old_name='LikeNotification',
            new_name='LikeNotificationModel',
        ),
        migrations.RenameModel(
            old_name='SaveNotification',
            new_name='SaveNotificationModel',
        ),
        migrations.RenameModel(
            old_name='TagNotification',
            new_name='TagNotificationModel',
        ),
    ]
