# Generated by Django 5.0.6 on 2024-07-29 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_rename_commentnotification_commentnotificationmodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follownotificationmodel',
            name='committer',
        ),
        migrations.RemoveField(
            model_name='follownotificationmodel',
            name='follow',
        ),
        migrations.RemoveField(
            model_name='follownotificationmodel',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='likenotificationmodel',
            name='committer',
        ),
        migrations.RemoveField(
            model_name='likenotificationmodel',
            name='like',
        ),
        migrations.RemoveField(
            model_name='likenotificationmodel',
            name='post',
        ),
        migrations.RemoveField(
            model_name='likenotificationmodel',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='savenotificationmodel',
            name='committer',
        ),
        migrations.RemoveField(
            model_name='savenotificationmodel',
            name='post',
        ),
        migrations.RemoveField(
            model_name='savenotificationmodel',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='tagnotificationmodel',
            name='committer',
        ),
        migrations.RemoveField(
            model_name='tagnotificationmodel',
            name='post',
        ),
        migrations.RemoveField(
            model_name='tagnotificationmodel',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='tagnotificationmodel',
            name='tag',
        ),
        migrations.CreateModel(
            name='NotificationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('follow', 'Follow'), ('like', 'Like'), ('comment', 'Comment'), ('save', 'Save'), ('tag', 'Tag')], max_length=128)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('text', models.CharField(blank=True, max_length=128, null=True)),
                ('committer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.postmodel')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
            },
        ),
        migrations.DeleteModel(
            name='CommentNotificationModel',
        ),
        migrations.DeleteModel(
            name='FollowNotificationModel',
        ),
        migrations.DeleteModel(
            name='LikeNotificationModel',
        ),
        migrations.DeleteModel(
            name='SaveNotificationModel',
        ),
        migrations.DeleteModel(
            name='TagNotificationModel',
        ),
    ]
